spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${JOB_DB_NAME:deharri-job-db}
    username: ${DB_USER:haris}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.deharri.jlds: INFO

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID:}
  secretKey: ${AWS_SECRET_ACCESS_KEY:}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: deharri-bucket

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /jobs/v3/api-docs
        name: Job Service API
    config-url: /jobs/v3/api-docs/swagger-config
    use-root-path: false
    operations-sorter: method
    display-request-duration: true
    tags-sorter: alpha
    disable-swagger-default-url: true
    url-prefix: /jobs

worker-sync:
  ttl-minutes: 60

jlds:
  internal:
    shared-secret: ${INTERNAL_SECRET:internal-secret-change-me}
