spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${JOB_DB_NAME:deharri-job-db}
    username: ${DB_USER:haris}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: secret.properties

server:
  port: 8083
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.deharri.jlds: DEBUG

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID:}
  secretKey: ${AWS_SECRET_ACCESS_KEY:}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: deharri-bucket

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    register-with-eureka: false
    fetch-registry: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

worker-sync:
  ttl-minutes: 60
